name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start app and run tests
      run: |
        npm run start & # ou outro comando para iniciar sua aplicação
        npx wait-on http://localhost:3000
        npm run cy:run

    - name: Generate Report
      run: |
        npm run cy:report
        npm run cy:report:html

    - name: Publish Report
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: mochawesome-report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


